// This file is generated by Gemini.

'use server';

/**
 * @fileOverview Image tag generation AI agent.
 *
 * - generateImageTags - A function that handles the image tag generation process.
 * - GenerateImageTagsInput - The input type for the generateImageTags function.
 * - GenerateImageTagsOutput - The return type for the generateImageTags function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GenerateImageTagsInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type GenerateImageTagsInput = z.infer<typeof GenerateImageTagsInputSchema>;

const GenerateImageTagsOutputSchema = z.object({
  tags: z.array(z.string()).describe('An array of tags generated for the image.'),
});
export type GenerateImageTagsOutput = z.infer<typeof GenerateImageTagsOutputSchema>;

export async function generateImageTags(input: GenerateImageTagsInput): Promise<GenerateImageTagsOutput> {
  return generateImageTagsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateImageTagsPrompt',
  input: {schema: GenerateImageTagsInputSchema},
  output: {schema: GenerateImageTagsOutputSchema},
  prompt: `You are an expert image tag generator.  You will generate tags that are relevant to the image, which will be used to improve searchability and moderate undesirable content.

  Photo: {{media url=photoDataUri}}
  `,
});

const generateImageTagsFlow = ai.defineFlow(
  {
    name: 'generateImageTagsFlow',
    inputSchema: GenerateImageTagsInputSchema,
    outputSchema: GenerateImageTagsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
